version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm i && npm run dist

workflows:
  version: 2
  build:
    jobs:
      - build_windows