version: 2
jobs:
  build_windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run: npm i --save-dev electron-builder && npm run dist
      - store_artifacts:
          path: /dist/skipLauncher Installer v*.exe
          destination: installer.exe

workflows:
  version: 2
  build:
    jobs:
      - build_windows